---
title: "example"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Example trajectory output

```{r libraries, message=FALSE}
library(tidyverse)
library(magrittr)
library(dyno)
set.seed(1)
```

Load data and wrap it as a dyno object.
```{r}
expression <- SCORPIUS::ginhoux$expression
counts <- 2^expression - 1 # I'm cheating because there is no counts data anymore

dataset <-
  wrap_expression(expression = expression, counts = counts)
```

Infer a trajectory with a certain TI method
```{r}
trajectory <-
  infer_trajectory(dataset, ti_projected_monocle(max_components = 3)) %>% 
  simplify_trajectory() %>% 
  add_root()
```

We can plot it using some of the dynplot functions:
```{r}
plot_dimred(trajectory)
plot_graph(trajectory)
plot_heatmap(trajectory, expression_source = dataset, label_milestones = FALSE, features_oi = 100)
```

Milestone network: required
```{r}
trajectory$milestone_network %>% write_tsv("data/milestone_network.tsv")
trajectory$milestone_network
```

Milestone percentages: required
```{r}
trajectory$milestone_percentages %>% write_tsv("data/milestone_percentages.tsv")
trajectory$milestone_percentages %>% head()
```

Divergence regions: optional
```{r}
trajectory$divergence_regions %>% write_tsv("data/divergence_regions.tsv")
trajectory$divergence_regions
```

Dimred: optional
```{r}
trajectory$dimred %>% as.data.frame %>% rownames_to_column("cell_id") %>% write_tsv("data/dimred.tsv")
trajectory$dimred %>% head()
```

Dimred milestones: optional
```{r}
trajectory$dimred_milestones %>% as.data.frame %>% rownames_to_column("cell_id") %>% write_tsv("data/dimred_milestones.tsv")
trajectory$dimred_milestones %>% head()
```

Dimred segments: optional
```{r}
# this method did not return dimred_segments so I'm manually
# creating an example table.
milnet <- trajectory$milestone_network
dimmil <- trajectory$dimred_milestones

dimred_segments <- 
  crossing(
    milnet %>% select(from, to),
    pct = seq(0, 1, by = .1)
  )

for (col in colnames(dimmil)) {
  dimred_segments[,col] <- dimmil[dimred_segments[,"from"], col] * (1-dimred_segments[,"pct"]) + dimmil[dimred_segments[,"to"], col] * dimred_segments[,"pct"]
}

dimred_segments %>% write_tsv("data/dimred_segments.tsv")
dimred_segments %>% head()
```

Order of milestones: optional
```{r}
trajectory$milestone_ids
```
